### ISSUE TITLE
Typeahead breaks if typeahead property receives NULL value

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-bootstrap#4417]
The typeahead directive breaks if the [typeahead] property receives a NULL value (with NullPointerException). This happens since my async data service returns NULL instead of [] if no search results were found.

I'm wondering why NULL is not a valid value? In my opinion, the directive should catch undefined values by itself.

```
ERROR TypeError: Cannot read property 'slice' of null
    at TypeaheadDirective.push../node_modules/ngx-bootstrap/typeahead/typeahead.directive.js.TypeaheadDirective.prepareMatches (typeahead.directive.js:306)
...
```

ngx-bootstrap: 3.0.0
Angular: 6.0.1

**Comment by pankmuze** [comment]
I am also facing the same issue. When there is nothing to return from the database for the API call, it is throwing the slice error and then I am unable to search anything anymore. 

Can someone help in this?

**Comment by pankmuze** [comment]
Can we use the typeaheadNoResults in anyway here?

**Comment by pankmuze** [comment]
Found a workaround. For the empty return value, I am making the API return an empty object, so the slice error is not coming up anymore. 

This empty object I have renamed as "No record found", so that when it is seen in the UI, it looks as though it is not returning anything.

In the TypeaheadOnSelect method, I am clearing the input field :-)

Hope this help others who are facing this issue
