### ISSUE TITLE
Dropdown basic-link has bad placement without class btn-group

### ISSUE THREAD

**Issue by probfacile** [valor-software/ng2-bootstrap#4426]
### Bug description
Using the example provided under id=basic-link, (and replacing the content with static list for speed), the Anchor dropdown doesn't work in a page flow. It will display dropdown after the end of the page.
The basic button example works as expected (included in the stackblitz).
I tryed adding the btn-group to the anchor-link span and it seems to work, so it might be a bug in the btn-group for picking container.

### StackBlitz that reproduces the issue:
https://angular-ngxbootstrapmodal.stackblitz.io

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.5

Angular: 5.0.0

Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:
check stackblitz

**Comment by tarusin** [comment]
@probfacile
Please, can you be more specific or/and provide a reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by jared-christensen** [comment]
I ran into this too. The drop-down menu is positioned absolute. So the container needs to be positioned, relative. It works in the documentation because it's wrapping container .bd-example has position relative. This is what it looks like using the example "dropdowns anchor trigger" straight from the documentation. https://valor-software.com/ngx-bootstrap/#/dropdowns#anchor-trigger 
![image](https://user-images.githubusercontent.com/1406482/48276205-13a3a680-e40d-11e8-95c4-dee1e1fa34c1.png)

In bootstraps documentation it looks like they wrap it with a dropdown class that sets the position to relative. You can see that here in the anchor example. https://getbootstrap.com/docs/4.1/components/dropdowns/#single-button

**Comment by Domainv** [comment]
This issue outdated
Please recheck in last version ngx-bootstrap@5.2.0
