### ISSUE TITLE
Datepicker shows correct date after selection but the actual value is different , it adds 22H in time

### ISSUE THREAD

**Issue by arangates** [valor-software/ng2-bootstrap#4464]
### Bug description or feature request:

i use BsConfig dateInputFormat : "DD-MM-YYYY" .

if i select a date it shows correct date for eg: i select 2018-07-26

actual value **2018-07-25T22:00:00.000Z**

expected value  **2018-07-26T00:00:00.000Z**

what i found is the day is reduced by 1 and it adds 22 hours in time. How to fix this ?

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:^3.0.1

Angular:6.0.0

Bootstrap:4.1.1

**Comment by Ashalyaa** [comment]
Hello

I am experiencing the same behaviour. Have you found a solution for this?

Selected value: 11.07.2018
Expected value:  2018-07-11T00:00:00.000Z
Actual value:  2018-07-10T22:00:00.000Z

I use the German locale ('de'), I thought at first it had maybe to do something with that, the behaviour is the same for the standard language. Other than the locale I don't use any different config.

Versions:
ngx-bootstrap: 3.0.1
angular: 6.0.6
bootstrap: 4.1.1

Cheers

**Comment by ghost** [comment]
@arangates this is due to the timezone component in the Date. You can you something like this
`const utcDate = new Date(Date.UTC(
   your_date.getFullYear(),
   your_date.getMonth(),
   your_date.getDate(),
   your_date.getHours(), 
   your_date.getMinutes()));
const resultDate = Json.stringify(utcDate);`
