### ISSUE TITLE
Datepicker Header UI not justify

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-bootstrap#4511]
StackBlitz: https://stackblitz.com/edit/angular-nsqjnf?file=src%2Fapp%2Fapp.component.html

Datepicker Header not justify

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1

Angular: 6.0.0

Bootstrap: 4.0.0

**Comment by frostbtn** [comment]
It's because there is not whitespace between the buttons by default since Angular 6. They have to put `&ngsp;` between `<button>`s or preserve whitespace in `bs-datepicker-navigation-view` component (`preserveWhitespaces: true` meta).

I haven't found any good solution for this problem myself other than a css hack. Put it just about anywhere as it adds a global style

```
::ng-deep .bs-datepicker-head bs-datepicker-navigation-view {
  display: flex;
  justify-content: space-between;
}
```

see https://stackblitz.com/edit/angular-765dls?file=src%2Fapp%2Fapp.component.css.

**Comment by ghost** [comment]
thank you, this work for me
