### ISSUE TITLE
event call on tab tag

### ISSUE THREAD

**Issue by Vips120** [valor-software/ng2-bootstrap#4699]
cant call custom click event method on a tab tag

**Comment by dukakent** [comment]
Hello @Vips120 ! Thank you for mentioning this issue. Unfortunately a click event is kind of tricky to fix right now because of the current legacy architecture of the tab component. However you can easily use `select` output according to the [API Reference](https://valor-software.com/ngx-bootstrap/#/tabs#tab-directive). There will be a brand new completely redesigned Tabs Component soon!

**Comment by Vips120** [comment]
Thnx for Ur reply but I did on my way :-)
