### ISSUE TITLE
bsDaterangepicker doesn't work with minMode 'month'

### ISSUE THREAD

**Issue by user753** [valor-software/ng2-bootstrap#5006]
Clicking in left datepicker do nothing but clicking in right datepicker somehow increase year.
```
<input type="text" bsDaterangepicker [bsConfig]="{minMode: 'month'}">
```
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.1.4

Angular: 7.1.4

Bootstrap: 4.1.3

**Comment by guibleme** [comment]
I'm experiencing the same thing; Looking at bspickerconfig class I just found out theres no minMode property there. I have no clue how to proceed.

**Comment by AbuHani** [comment]
i have same issue,when use minMode in daterangepicker config

**Comment by 0x054** [comment]
Yep, same problem here! Doesn't work with 'year' either.  Any news on a fix??

**Comment by marie-dk** [comment]
I am creating a birth date picker and realized that it is much easier to select year, then switch view to month, and then to day. This way the user can select date of birth in just 3 clicks.

But when starting view mode in 'year' bsDatePicker refuse to switch date to the selected year. When switching to month view, the title should reflect the year selected, but it doesn't. It picks a certain year and refuse to change to the year picked by the user.
The same happens when picking the month.

So I made a very ugly workaround by making each select handler set the date and change view mode to the next step, then opening the calendar again. Hopefully the close/open will be too quick for the user to notice.

Well, code says more than a thousand words. This is my hack: [Stackblitz: ngx datepicker year->month->day workaround](https://stackblitz.com/edit/ngx-datepicker-year-month-day-workaround)

**Comment by simonabler** [comment]
Same here

**Comment by cnthiesen** [comment]
Same 😭

**Comment by vishranti5** [comment]
any updates on same?

**Comment by vishranti5** [comment]
Hi,
i have used DateRangePicker of ngx-bootstrap. its minMode set to month in bsconfig but it is not working. If i click on selecting month it is somhow increasing year in right datepicker.
The same thing is working fine with Datepicker. The problem is with DateRangePicker only.

can someone help me with same

**Comment by indexlang** [comment]
same problem as minMode set to "Year"

**Comment by GuppuBoss** [comment]
When setting Date Range picker to min mode month. Calender view shows perfect. But clicking on date does not do anything
Using **"ngx-bootstrap": "^4.2.0",**

**Comment by calldeludo** [comment]
In the version "ngx-bootstrap": "^5.1.0".
 [bsConfig]="{minMode: 'month'}" shows the view good but is not working.

**Comment by simon-knu** [comment]
Same issue on 5.3.0 when mode is on "year"
It appears but we can't do anything

**Comment by Louer-un-manager** [comment]
Min mode is not working with DateRangePicker. Someone find a solution?
For my part i created two calendars in Min Mode Month, then selecting the first Year and Month in the first calendar will create a [minDate]="minDate" with the minDate of the first calendar.

```
<div *ngSwitchCase="'textDateDebut'" class="input-group">
                                        <div class="input-group-prepend">
                                          <span class="input-group-text">
                                            <fa-icon [icon]="faCalendar" class="glyphicon glyphicon-user form-control-feedback"></fa-icon>
                                          </span>
                                        </div>
                                        <input type="text" [formControlName]="prop.key" class="form-control" bsDaterangepicker #dp="bsDaterangepicker" [bsConfig]="bsConfig" placeholder="Sélectionnez une date de début" (bsValueChange)="onValueChange($event)">
                                      </div>

                                      <div *ngSwitchCase="'textDateFin'" class="input-group">
                                        <div class="input-group-prepend">
                                          <span class="input-group-text">
                                            <fa-icon [icon]="faCalendar" class="glyphicon glyphicon-user form-control-feedback"></fa-icon>
                                          </span>
                                        </div>
                                        <input *ngIf="minDate" type="text" [formControlName]="prop.key" class="form-control" bsDatepicker #dp="bsDatepicker" [bsConfig]="bsConfig" placeholder="Sélectionnez une date de fin" 
                                        [minDate]="minDate">
                                      </div>
```

```
bsConfig: Partial<BsDatepickerConfig>;
  data: Date;
  minDate: Date;

ngOnInit() {
    /** On affiche seulement les mois et l'année */
    this.bsConfig = Object.assign({}, {
      minMode : this.minMode
    });
  }//END ngOnInit

  onValueChange(value: Date): void {
    this.data = value;
    this.minDate = this.data;
  }
```

**Comment by filipiz** [comment]
In my context, I'd like to select a range of months or a range of years.
`minMonth` makes calendar render properly. 

But the click events on the months does not select the range (as it does with `minMonth='day'`

**Comment by zaniniflz** [comment]
Same for me. Any updates?
