### ISSUE TITLE
Error __WEBPACK_IMPORTED_MODULE_0__angular_core__.Injector.create is not a function

### ISSUE THREAD

**Issue by IvanRyavkin** [valor-software/ng2-bootstrap#5114]
hi

### Bug description:

by an example https://valor-software.com/ngx-bootstrap/old/3.2.0/#/modals#service-section

```json
ERROR TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.Injector.create is not a function
    at ComponentLoader.show (ngx-bootstrap-component-loader.js:153)
    at BsModalService._showBackdrop (ngx-bootstrap-modal.js:894)
    at BsModalService.show (ngx-bootstrap-modal.js:855)
```

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.2.0

Angular: 4.4.7

Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack

webpack

**Comment by ludmilanesvitiy** [comment]
@IvanRyavkin Please provide a reproduction via stackblitz
Starter template:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by IvanRyavkin** [comment]
@ludmilanesvitiy hi
https://stackblitz.com/edit/ngx-bootstrap-ckfvhg

**Comment by ludmilanesvitiy** [comment]
@IvanRyavkin Thank you for reproduction. This happens because of versions incompatibility. 
For ngx-bootstrap 3.*.*  use @angular dependencies ~6
For ngx-bootstrap 4.*.*  use @angular dependencies ~6,7
In your example I've updated dependencies to the latest and modals works as expected:
![Peek 2019-03-26 11-20](https://user-images.githubusercontent.com/18209841/54985515-980c5580-4fb9-11e9-8d3d-891c141c2a75.gif)

**Comment by IvanRyavkin** [comment]
we can't update angular to version 6 now(((

**Comment by ludmilanesvitiy** [comment]
For angular 4 will be compatible 2.0.0 version of ngx-bootstrap: https://github.com/valor-software/ngx-bootstrap/blob/development/CHANGELOG.md#200-2018-01-19

**Comment by ludmilanesvitiy** [comment]
Closed due to using incompatible version.
