### ISSUE TITLE
Typeahead suggestions width do not scale

### ISSUE THREAD

**Issue by eserkansozer** [valor-software/ng2-bootstrap#5149]
In mobile view when it does not fit to screen width, the suggestions do not wrap into next line

**Comment by ludmilanesvitiy** [comment]
Steps to Reproduce:
1.Open Typeahead in Mobile
2. Add to the states array very long name or any sentence
3. See the current results:
![Screenshot from 2019-04-11 11-11-57](https://user-images.githubusercontent.com/18209841/55941393-cbeaaa80-5c4a-11e9-9cdf-1d66b7b4891e.png)

Expected result: the long State should be divided into few lines for making suggestions readable

**Comment by IraErshova** [comment]
@eserkansozer Hi! Thanks for your comment. The reason why the line doesn't wrap into the next line is because of bootstrap styles. Each item has class `.dropdown-item`, which set up `white-space: nowrap;`.

If you want to change this behaviour you have to override bootstrap's styles, e.g. to this:
`white-space: normal;`.

**Comment by eserkansozer** [comment]
Thanks very much, it worked!
