### ISSUE TITLE
ngx-bootstrap isn't working with ivy

### ISSUE THREAD

**Issue by robertIsaac** [valor-software/ng2-bootstrap#5257]
### Bug description or feature request:
when building the angular application `ng build` with ivy enabled it throw the following error
> ERROR in Expected array when reading property declarations

for any package i'm using (tried alert, tabs and pagination)
i think (but not sure) the problem is with the datepicker
because before throwing the error it shows
`Compiling ngx-bootstrap/datepicker : module as esm5`

### StackBlitz that reproduces the issue:
using the starter templates without any edit other than making ivy enabled will throw the error

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.2.0

Angular: 8.0.0

Bootstrap: NA

### Build system: Angular CLI

**Comment by tloten** [comment]
This is likely caused by the use of the spread operator in the module declarations and/or exports section: https://github.com/valor-software/ngx-bootstrap/blob/development/src/datepicker/bs-datepicker.module.ts

I've tried fixing them up by hand and I'm still getting the error - I there are a few more modules that are using that convention that I haven't found yet.

For reference, this is the discussion around it in the Angular project: https://github.com/angular/angular/issues/29835

**Comment by tloten** [comment]
Poked around some more - I was only changing the esm5 version. Doing the same manual hack to the fesm5 version and Ivy is now compiling it fine.
