### ISSUE TITLE
tooltip manual trigger issue with focus

### ISSUE THREAD

**Issue by SelfishLucho** [valor-software/ng2-bootstrap#5613]
Bug description:

Using the input `triggers="focus"` does not dismiss the tooltip with manual triggering

Plunker/StackBlitz that reproduces the issue:

https://stackblitz.com/edit/ngx-bootstrap-tooltip-trigger-bug?file=app%2Ftriggers-manual.html

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.4.0

Angular: 8.0.0

Bootstrap: 4

Build system: Angular CLI, System.js, webpack, starter seed:

**Expected behavior**

When adding `triggers="focus"` should work as regular tooltip and dismiss the tooltip or if not designed that way possibly add that feature along with manual triggering.

**Comment by IraErshova** [comment]
Hi @SelfishLucho! I see your problem, but that's not a bug of ngx-bootstrap. The problem is that you used HTML element which is not focusable.

I've updated your example in StackBlitz. Could you please check it?

[https://stackblitz.com/edit/ngx-bootstrap-tooltip-trigger-bug-6dqjg9](https://stackblitz.com/edit/ngx-bootstrap-tooltip-trigger-bug-6dqjg9)

Also, I added information about focusable elements to the example.
