### ISSUE TITLE
datepicker is invalid, but returns no errors when using setValidator 

### ISSUE THREAD

**Issue by robvaneck** [valor-software/ng2-bootstrap#5656]
Please see:

https://stackblitz.com/edit/angular-9nrqgu

**Comment by sonicpro** [comment]
I'm going to investigate this.

**Comment by sonicpro** [comment]
@borriej, there is probably an issue with you code on https://stackblitz.com/edit/angular-9nrqgu.
`startDate` control has both `BsDatePickerInputDirective` validator as well as the built-in `required` validator. The first one is attached through `bsDatepicker` directive in `custom-input-date.component.html`, the second one - programatically in `app.component.ts` constructor.

`endDate` control, on the other hand, has only BsDatePickerInputDirective validator attached initially. Then, when `oneDay` control fires `valueChanges`, the validator is replaced by the built-in `required` validator. When this is the case, only "empty" value is considered invalid for `endDate`, any malformed dates that is supposed to be checked by `BsDatePickerInputDirective` do not cause `endDate.status` change to "invalid".

I suggest you to concatenate `BsDatePickerInputDirective` validator and a new `required` validator into a single validator function by means of `Validators.compose`.  The fix is depicted in the attachment.
![Untitled](https://user-images.githubusercontent.com/5416927/74864151-c0323f00-5357-11ea-90f6-7a557e6bdf70.png)
