### ISSUE TITLE
Accordion [isOpen] isn't correctly responsive.

### ISSUE THREAD

**Issue by Gustafssonz** [valor-software/ng2-bootstrap#5686]
Bug description:
Using a Chevron Up/Down at the end of header, together with isAnimated it bugs out if pressed to fast on the button.

Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngx-bootstrap-accordion-bug

Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 5.5.0
angular: 9.0.2

**Expected behavior**
The accordion is expected to adjust the Chevron Up/Down icon depending on the [isOpen] input. While it is working if you press each time slowly, it does not behave correctly when dubbel click. 
Dubbel click the button should create the bug.

**Comment by daniloff200** [comment]
Well, yeah, that definitely works not 100% correct.
Looks like some issue with isAnimated, because, if turn this off via **[isAnimated]="false"**  value, the issue doesn't exist (at least, for me). Could you, please, confirm that too? @Gustafssonz 

If so, then, if you don't need animation for Accordion, you can turn it off.
For other case, I'm gonna work on a fix started  from Monday

**Comment by Gustafssonz** [comment]
Hello @daniloff200 ! 
You are correct, turning isAnimated="false" is solving the problem but we really need that animation (otherwise our UX pepps will get mad).
I am a pretty new dev so it would be a nice learning for me if you could explain the steps you do to solve it later on :) (if it's too complex, otherwise I'll just read your PR).

**Comment by IraErshova** [comment]
@daniloff200 We have to check this issue with [this PR](https://github.com/valor-software/ngx-bootstrap/pull/5675/files). Maybe it resolves the problem.
