### ISSUE TITLE
Create Select Component

### ISSUE THREAD

**Issue by NenadJovicic** [valor-software/ng2-bootstrap#5743]
**Is your feature request related to a problem? Please describe.**

What would be nice to have as a new component is `<select></select>` where you can store as a value whole object that you have.

Because, I like this package for bootstrap, but I have to manually create my `select` tag and to track items by index and change objects manually every time when I use `select` 
because default html `select` and `option` can store only simple values like numbers or strings inside `value` property.

How it looks for now:
```html
      <select [(ngModel)]="selectedUser"
              class="form-control">
        <option *ngFor="let user of users; let i = index"
                value="{{i}}">
          {{user.firstName + " " +user.lastName}}
        </option>
      </select>
```

Where `selectedUser` is currently `number` and then, when I want to get actual users in some TS file, I have to manually call `this.users[this.selectedUser]` to actually access proper object

**Describe the solution you'd like**

For example, I have list of users, and I want to have them as `<option></option>` for `select`, and I want to show their first and last name inside `option`. I would like the value of this `select` with `ngModel` or some form, and I would like that on every change, it actually returns me whole object

code example
```html
<ngx-select [(ngModel)]="selectedUser">
    <ngx-option *ngFor="let user of users" [value]="user">
        {{ user.firstName + ' ' + user.lastName}}
    </ngx-option>
</ngx-select>
```
Good example of this would be https://material.angular.io/components/select/overview

**Describe alternatives you've considered**

Was thinking about dropdown, but it is not the best solution, because, first of all, it won't do highlighting what is selected, and I always have to change text of button manually.

**Additional context**

**Comment by TheOnlyReadOnly** [comment]
You don't need a new component to do this. Just use `select` with `[ngValue]` on options instead of `value` or `[value]`: [StackBlitz](https://stackblitz.com/edit/angular-ewdzac)

See also [Angular API docs for NgSelectOption](https://angular.io/api/forms/NgSelectOption)

Remember that the selected item is chosen with a simple comparison between object references so be sure that `ngModel` is one of `ngValue`s and not just an object with same properties and values. See "Not working" on StackBlitz. Your `ngx-select` would have the same problem, unless providing a custom object comparing function.

**Comment by NenadJovicic** [comment]
Thanks for help @TheOnlyReadOnly 
guess I can close this issue then
