### ISSUE TITLE
Design breaking on pagination arrows

### ISSUE THREAD

**Issue by sujithmathewthomas** [valor-software/ng2-bootstrap#5756]
Bootstrap Pagination left and right arrow buttons are broken from update 5.6.0 onwards

**Comment by daniloff200** [comment]
Any info about that?

Could you please create a repro with a stack blitz (https://stackblitz.com/edit/angular-tmeitv?file=main.ts), or, github repo, that shows the issue?

**Comment by sujithmathewthomas** [comment]
I wanted to replace the next and previous button texts with arrow icons. So I've been using fa-icons as follows. It was working fine till 5.5.0, but after the update is is broken.

<pagination class="pagination-sm"
            [(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage"
            [maxSize]="maxSize" [directionLinks]="true" [boundaryLinks]="false"
            [rotate]="false"
            previousText='<i class="fa fa-angle-left" aria-hidden="true"></i>'
            nextText='<i class="fa fa-angle-right" aria-hidden="true"></i>'
            (pageChanged)="pageChange(config, $event)" (numPages)="numPages = $event">
 </pagination>

**Comment by sujithmathewthomas** [comment]
@daniloff200 
I wanted to replace the next and previous button texts with arrow icons. So I've been using fa-icons as follows. It was working fine till 5.5.0, but after the update to 5.6.0,it is broken.

`<pagination class="pagination-sm"`
`[(ngModel)]="page" [totalItems]="length" [itemsPerPage]="itemsPerPage"`
`[maxSize]="maxSize" [directionLinks]="true" [boundaryLinks]="false"`
`[rotate]="false"`
`previousText='<i class="fa fa-angle-left" aria-hidden="true"></i>'`
`nextText='<i class="fa fa-angle-right" aria-hidden="true"></i>'`
`(pageChanged)="pageChange(config, $event)" (numPages)="numPages = $event">`
`</pagination>`

**Comment by sujithmathewthomas** [comment]
Any update on this?

**Comment by setiseta** [comment]
I think the intended way is now with the ng-templates, or am i wrong @daniloff200 
Example is here: https://valor-software.com/ngx-bootstrap/#/pagination#custom-template
There was a behavior change with PR #5661 
Befor this it was possible to pass html to the '*Text' (eg. nextText) variables.
It was displayed correctly because this text was set as `[innerHTML]` on the `a` tag
```
<a class="page-link" href (click)="selectPage(page + 1, $event)"
   [innerHTML]="getText('next')"></a>
```
Now after thie PR the default template is for example:
`<ng-template #defaultNextTemplate>{{ getText('next') }}</ng-template>`
this will display all html tags as text.

If this behavior was not intended, i can do a new PR.

example for the icons:
```
<pagination
  ...
  [customPreviousTemplate]="prevTemplate"
  [customNextTemplate]="nextTemplate">
</pagination>
<ng-template #prevTemplate><i class="fa fa-angle-left" aria-hidden="true"></i></ng-template>
<!-- or if you have the icon in a variable, or from a function-->
<ng-template #nextTemplate><span [innerHTML]="iconService.get('angle-right')"></span></ng-template>
```

**Comment by sujithmathewthomas** [comment]
Thanks @setiseta . It's working now.
