### ISSUE TITLE
Error in selected days visualization when showWeekNumbers is set to false in DateRangePicker

### ISSUE THREAD

**Issue by JoseLlorensRipolles** [valor-software/ng2-bootstrap#5868]
Bug description:

When using the date range picker component, the view for selected days is different if the week number is shown or not ( showWeekNumbers: false ). 

Example of the selection with week numbers:
![imagen](https://user-images.githubusercontent.com/10089812/88052121-0cc5b480-cb5a-11ea-8634-b30c83c0b0ce.png)
This can be seen at : https://valor-software.com/ngx-bootstrap/#/datepicker#date-initial-state

Example of selection without week numbers:
![imagen](https://user-images.githubusercontent.com/10089812/88052253-4696bb00-cb5a-11ea-943b-70eb1e7e4c47.png)
This can be seen at: https://valor-software.com/ngx-bootstrap/#/datepicker#format

Versions of ngx-bootstrap, Angular, and Bootstrap:

Examples taken from the documentation (https://valor-software.com/ngx-bootstrap/#/datepicker)

Build system: Angular CLI, System.js, webpack, starter seed:

Examples taken from the documentation (https://valor-software.com/ngx-bootstrap/#/datepicker)

**Expected behavior**

Same view, without separation between days

**Comment by daniloff200** [comment]
Woah, that's look really strange!
Thanks for finding this out!

I should say, I've never seen such things before, so, maybe that can be related to migration to Angular 9, somehow
Anyway, gonna check that this week, and, try to fix

Thanks again, @JoseLlorensRipolles  for that!

**Comment by JoseLlorensRipolles** [comment]
Hey! Thank you for your quick response!

I actually found this on a project using: 

ngx-bootstrap: 5.3.2
Angular: 8.2
Bootstrap: 4.4.0

I just thought that it would be clearer if reported directly from documentation, but it may help you if you think the problem is migration related. 

Thank you very much!!

**Comment by daniloff200** [comment]
Ah, so looks like it's not related to migration, maybe, it was broken from the beginning :laughing: 

Will check :)

**Comment by daniloff200** [comment]
Well, I found that this issue exist even in 3+ versions of ngx-bootstrap, which are sooooo ooold. 
I've also found an interesting case , check my screenshot below

It looks like, that issue with spaces appears only for 4th day in week row, which is even more strange
![Selection_045](https://user-images.githubusercontent.com/13692220/88219957-02471000-cc6b-11ea-906b-a989b2ae6179.png)

This issue is really old, and nobody saw that, looks like, nobody hides weekNumbers for daterangepicker :rofl: 

Thanks again for finding that, @JoseLlorensRipolles ! 
Fix will be ready soon, and, available in next release, I suppose, in the beginning of the August

**Comment by JoseLlorensRipolles** [comment]
Awesome work! Thank you very much Dmitriy!
