### ISSUE TITLE
Support Angular 12

### ISSUE THREAD

**Issue by eric-simonton-sama** [valor-software/ng2-bootstrap#6108]
Angular 12 is officially released now. This is a feature request for ngx-bootstrap to officially support it. Currently [it looks like](https://github.com/valor-software/ngx-bootstrap#compatibility) only up to Angular 10 is supported.

Thank you for the nice library!

**Comment by Karan653** [comment]
We have a requirement to upgrade to Angular 12 .Since IVY is default compilation and rendering engine in Angular 12, ngx-bootstrap 6.2.0  on  compilation with Angular 12 is throwing error (ngcc failed to run on bootsrap 6.2.0). Can you please help out in letting us know if there is any planned release for the same?. This would be of great help.

**Comment by Dassderdie** [comment]
> We have a requirement to upgrade to Angular 12 .Since IVY is default compilation and rendering engine in Angular 12, ngx-bootstrap 6.2.0 on compilation with Angular 12 is throwing error (ngcc failed to run on bootsrap 6.2.0). Can you please help out in letting us know if there is any planned release for the same?. This would be of great help.


According to the `Readme` Angular 12 will only be supported with `^7.0.0`:
<html>
<body>


7.0.0 | 11.x.x - 12.x.x | 3.x.x or 4.x.x
-- | -- | --
6.0.0 | 9.x.x - 10.x.x | 3.x.x or 4.x.x


<br class="Apple-interchange-newline">
</body>
</html>

There is already `7.0.0-rc.1` published via npm so you could potentially try that.

@valorkin Is there already an ETA for a stable release of version 7?

**Comment by eric-simonton-sama** [comment]
v7.0 was released this morning, and as Dassderdie says the readme says it supports Angular 11-12. Thank you!
