### ISSUE TITLE
Button tooltip overflows page on right side

### ISSUE THREAD

**Issue by swnf** [valor-software/ng2-bootstrap#6169]
Bug description: A button tooltip on the right side of the page is not automatically aligned with the page's boundary and causes an overflow. Tooltips work correctly on the left side.

Plunker/StackBlitz that reproduces the issue: https://stackblitz.com/edit/ngx-bootstrap-tooltip-issue

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 7.0.0-rc.1

Angular: 11.2.14

Bootstrap: 4.6.0

Build system: Angular CLI

**Expected behavior**

The tooltip should be automatically moved to the left by the [`preventOverflow` modifier](https://github.com/valor-software/ngx-bootstrap/blob/1abff402a2b05cbafdec6d6a952e006e253b5164/src/positioning/modifiers/preventOverflow.ts). This bug did **not** appear in ngx-bootstrap 6. I'm not entirely sure but I think this bug is caused by a [typo replacing `>` with `<`](https://github.com/valor-software/ngx-bootstrap/commit/51051bd6e0b9c9e9ecb05b271e4ec08fd9970358#diff-a3b6b5803e9980e3dfca659934ae3d22f16be4e4f4e3686ba328cc30c7ffc741R50).

**Comment by vguillou** [comment]
Same issue with popover placement and adaptive position, and same expected behavior:
https://stackblitz.com/edit/ngx-bootstrap-sker7j-zdqmsk?file=app%2Fadaptive-position.html

ngx-bootstrap: 7.0.0
Angular: 12.2.0
Bootstrap: 4.5.3

**Edit:** Took the liberty to open [the following PR](https://github.com/valor-software/ngx-bootstrap/pull/6268).
I did not implement any test, as there are none yet for the `positioning` module. Open to help on that front if you give me some pointers on how you would want to mock the DOM API and your utils (not tested either). 🙂 
I suppose that would not prevent a merge though, as it fixes an obvious regression due to a typo.
