### ISSUE TITLE
Documentation not available due to "https://valor-software.com/" down

### ISSUE THREAD

**Issue by eswarvijji** [valor-software/ng2-bootstrap#6277]
**Description:**
Hi Team,
We are unable to access the documentation due to "https://valor-software.com/" site is down.

Regards,
Eswara
![dw](https://user-images.githubusercontent.com/30665308/131618556-0933e014-2e7a-4732-ac5e-9fefc1007d15.JPG)

**Comment by daniloff200** [comment]
Well, that's strange, because

https://downforeveryoneorjustme.com/valor-software.com says that it works correctly, and, for me also

We get the same question about site availability month ago from other folks, but, they just tried to change the network, and it worked
@eswarvijji , could you, maybe, give us some more details?

**Comment by eswarvijji** [comment]
Hi Team,
Still no luck, 
we have tried to access from different devices and networks. **### Getting error "182.79.218.106 refused to connect".**
and we are accessing from India.
If you required more information . feel free contact.

Regards,
--
Eswara
+91 8971 546 546

**Comment by eswarvijji** [comment]
Hi Team,
What a surprise, 
If I connect my mobile internet ,it is accessing.
but in through my WI-FI , it is not accessing.
any how thank you for support.

Regards,
--
Eswara
