### ISSUE TITLE
Missing CSS-Classes when using placement="right | left" on Tooltip

### ISSUE THREAD

**Issue by alexanderfink** [valor-software/ng2-bootstrap#6278]
**Bug description:**
When using placement="right" or placement="left" or even placement="auto" (and it displays the tooltip on left/right side) the tooltip arrow is missing. (See Screenshot)

![Missing Tooltip-Arrow](https://user-images.githubusercontent.com/30551988/131956005-b345e572-7b31-44f7-a7d8-e0f6eabd46d7.png)

When comparing tooltips with `placement="left | right"` with tooltips using `placement="top | bottom"` I noticed that they are missing a few (automatically added?) classes. See the comparison I created. (Might need to download it [2000x3000].

_TL:TR:_ Tooltips using `placement="right | left"` are missing placement associated classes like `.bs-tooltip-top, .bs-tooltip-auto[data-popper-placement^=top]` on several elements although they are added in the HTML-Element but no styles-classes seem to apply. 

![TooltipDifference](https://user-images.githubusercontent.com/30551988/131956153-37fed779-56e4-4c19-9797-2c53af82df0f.png)

**Versions of ngx-bootstrap, Angular, and Bootstrap:**

ngx-bootstrap: 6.2.0
Angular: 12.1.1
Bootstrap: 5.0.2

**Expected behavior**

An arrow should be displayed on the left / right side of the tooltip

**Comment by daniloff200** [comment]
Hi, @alexanderfink 
It's very strange for me, that you were able to build everything with such combination of dependencies, because,  Bootstrap 5 support was added only with ngx-bootstrap 7.1.0 version, also, even if it worked correct with Angular 12, we added support for that in 7 version too

I think, you can try at first to update ngx-bootstrap version in your app to latest one, it's 7.1.0

**Comment by valorkin** [comment]
should be fixed in 7.1
