### ISSUE TITLE
The enabled dates month is not enabled after switching to the month view mode

### ISSUE THREAD

**Issue by orestisioakeimidis** [valor-software/ng2-bootstrap#6406]
When the `datesEnabled` option is used, the month that the enabled dates belong to is not enabled after switching to the month view mode.

You can reproduce it on the ngx-bootstrap official docs website using the following link. Use the left arrow to go back to February 2020. You can see the enabled dates, but if you click on February, the month view is displayed but February is disabled.

https://valor-software.com/ngx-bootstrap/old/7.1.2/#/datepicker#dates-enabled

ngx-bootstrap: 7.1.2

Angular: 12.2.15

Bootstrap: 5.1.3

Build system: Angular CLI

**Expected behavior**

The month(s) that the enabled dates belong to should be enabled when switching to the month view mode.

**Comment by valorkin** [comment]
yes, that's correct
there are a PR to be merged https://github.com/valor-software/ngx-bootstrap/pull/6315
and issue #6311 which describes it

thanks for reporting, and subscribe to initial issue or PR
closing as duplicate

**Comment by SvetlanaMuravlova** [comment]
@orestisioakeimidis thank you for your issue, it is already fixed in current version
you also can check it here https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview#dates-enabled
so i will close this issue, but if something is wrong, don't hesitate to reopen it with some new comment and details
![image](https://user-images.githubusercontent.com/83700465/149768633-2f320903-6832-4704-b3e3-2406dc0b2c04.png)
