### ISSUE TITLE
Critical : Focus trapped in Radio with radio group component

### ISSUE THREAD

**Issue by rsathyamoorthy12** [valor-software/ng2-bootstrap#6427]
Tab and shift tab work in all the button except the Radio with radio group scenario.

All the keyboard users and the 508 testers having problem when the user Shit+Tab from the component.

![image](https://user-images.githubusercontent.com/6904268/151703963-fbf15d9d-9384-4de8-a02d-e85ea6167a42.png)

**Comment by SvetlanaMuravlova** [comment]
hi, @rsathyamoorthy12 , thank you for your issue, but you are working with elements as radiogroup, so navigation inside should be with arrow buttons https://www.w3.org/WAI/ARIA/apg/patterns/radiobutton/

**Comment by roxyska** [comment]
Hello,

In fact, the problem is we can't navigate **outside** radioButtonGroup with `Shift` + `Tab`. 
Currently when we navigate with keyboard and use `Shift` + `Tab` from radioButtonGroup we're trapped. We can only use `Tab` to access next focussable element but we can't access to the previous one.
