### ISSUE TITLE
Modal created via BsModalService is not hidden after calling .hide() due to animation delay

### ISSUE THREAD

**Issue by ISeeBinary** [valor-software/ng2-bootstrap#6439]
Bug description:

If you call hide on a modal created via BsModalService.show(Component) before the animation has completed, the modal doesn't hide and is left on screen. 

It looks like a similar issue was raised back in [2018](https://github.com/valor-software/ngx-bootstrap/issues/3711) and a fix implemented. I have been able to do a similar thing to the fix and put the hide inside a setTimeout with a delay equivalent to TRANSITION_DURATIONS.MODAL (300ms)

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 8.0.0

Angular: 13.1.4

Bootstrap: 3.3.7

Expected behavior:

Calling hide hides the modal regardless of animation state

**Comment by alejandrocoding** [comment]
Hi @valorkin - this is still an issue, I wonder if there is opportunity for us to help sending a PR.

Is the fix suggested above valid? any other direction you wanna us go to? any blockers for this?

I am interested in helping with this issue too: https://github.com/valor-software/ngx-bootstrap/issues/6441

**Comment by bakermeoe** [comment]
how about using bsModalService .hide() function? 

Edit: I know this already been fixed in v8 or later, but if I still want to use v7.1.2, 
is using bsModalService .hide() a good approach?

I just realized, ngx-bootstrap documentation doesn't inform this function. I saw the library code, there is .hide() function inside BsModalService class.
but the version of ngx-bootstrap is different with you, mine is v7.1.2

![image](https://user-images.githubusercontent.com/11452447/235829958-9e46e72f-8202-48a2-91ac-d5b341ab6232.png)
