### ISSUE TITLE
Update to angular 14.0

### ISSUE THREAD

**Issue by kyrolus** [valor-software/ng2-bootstrap#6482]
**Description:**
Could you please update this great package to use angular 14.0

**Comment by dionatan-g** [comment]
Up!

**Comment by mrs-cp** [comment]
we'd appreciate that, too 👍

**Comment by royeradames** [comment]
I support it. Angular 14 brings Form generics that feature is essential.


# Remove package until it support angular 14 or downgrade to angulate 13
## Buggy solution: This can solve the issue until it gets updated (noting it here because you may have heard about this):
`.npmc` file with `legacy-peer-deps=true` sibling to your node_modules directory

Sources:
- https://docs.npmjs.com/cli/v8/configuring-npm/npmrc#per-project-config-file
- https://stackoverflow.com/a/66099631/3044126

**Comment by kyrolus** [comment]
It is already updated. Thanks.

**Comment by kyrolus** [comment]
No, it is updated on the ngx-bootstrap website https://valor-software.com/ngx-bootstrap/#/ with version 9.0.0-RC1, but in npm the version is 8.0.0

**Comment by valorkin** [comment]
9.0.0-RC.2 is on npm
available as @next version 
this week testing, if nothing critical related to ng14 - releasing as @latest on Friday
mention me if you will find anything
