### ISSUE TITLE
schematics for ngx-bootstrap 9.0.0 doesn't work

### ISSUE THREAD

**Issue by SvetlanaMuravlova** [valor-software/ng2-bootstrap#6505]
should be fixed command 'ng add ngx-bootstrap' for ngx-bootstrap 9.0.0 with angular 14
<img width="1352" alt="Screenshot 2022-09-14 at 12 49 05" src="https://user-images.githubusercontent.com/83700465/190121979-c2026b3d-3384-488f-98c7-a0f3c689f375.png">

**Comment by Rich-Hopkins** [comment]
I have this same issue. I see that PR 6508 fixed it, but I don't see what I need to do to get it working. I've asked in the slack group, and I see a StackOverflow question that doesn't have a helpful answer, so no point in asking the same thing again there. What do I need to do in order to get the code that works?
