### ISSUE TITLE
[question] ngx-boostrap 11 and bootstrap 3

### ISSUE THREAD

**Issue by devildant** [valor-software/ng2-bootstrap#6606]
**Description:**
hello, during the migration of my application from a14 to a16, I noticed with dismay that bootstrap 3 was no longer supported (setTheme('bs3') return an error)
is there a solution to keep using it ? (ngx-boostrap 11 with bs3)
because the cost of a migration to bs4 or higher is pharaminous on my project

best regards

**Comment by StefanTirea** [comment]
Hi @devildant ,
first up: I am not connected to this project at all. Just a fellow library user.

The documentation states that Angular 14 is the last version to support BS3.

I checked the difference between v10 and v9 of ngx-bootstrap and you can [see that they removed BS3](https://github.com/valor-software/ngx-bootstrap/commit/fd8a29669e2cea3232706ee73ad15c2992411f7f#diff-6221c8aed29d4f95168e2926cc8a6d99d2c4ac5de44929d88757689534b4ddacR3) completely from the project (including all references). Unfortunately, there seems to be no possibility to use the newer version of ngx-boostrap.

When you use the old ngx-bootstrap version with a new Angular version, you will get the peer-dependency error. One way to bypass this issue is to use `npm install --legacy-peer-deps` to willfully **ignore** the Angular version requirement. However, I cannot tell you if you will see any issues regarding this, you will need to try it out.

Hope I could help a little bit.
Cheers!

**Comment by devildant** [comment]
> Hi @devildant , first up: I am not connected to this project at all. Just a fellow library user.
> 
> The documentation states that Angular 14 is the last version to support BS3.
> 
> I checked the difference between v10 and v9 of ngx-bootstrap and you can [see that they removed BS3](https://github.com/valor-software/ngx-bootstrap/commit/fd8a29669e2cea3232706ee73ad15c2992411f7f#diff-6221c8aed29d4f95168e2926cc8a6d99d2c4ac5de44929d88757689534b4ddacR3) completely from the project (including all references). Unfortunately, there seems to be no possibility to use the newer version of ngx-boostrap.
> 
> When you use the old ngx-bootstrap version with a new Angular version, you will get the peer-dependency error. One way to bypass this issue is to use `npm install --legacy-peer-deps` to willfully **ignore** the Angular version requirement. However, I cannot tell you if you will see any issues regarding this, you will need to try it out.
> 
> Hope I could help a little bit. Cheers!

Hello @StefanTirea, thx for your reply,
that's what I feared, I also looked without success. legacy mode could allow me time to either migrate bootstrap or remove ngx-bootstrap to keep only the css

best regards
