### ISSUE TITLE
Pagination component throwing ExpressionChangedAfterItHasBeenCheckedError and not setting correct page

### ISSUE THREAD

**Issue by rchowdev** [valor-software/ng2-bootstrap#6703]
Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 18.1.3

Angular: 18.1

Bootstrap: Bootstrap 5.3

Build system: Angular CLI, System.js, webpack, starter seed:

https://stackblitz.com/edit/stackblitz-starters-3g2oxv?file=package.json,src%2Fapp%2Fpagination%2Fpagination.component.ts

**Expected behavior**

Steps to reproduce:

1. Start on page 10 and limit 10. 
2. Set limit to 50.

I expect the page to be set to 1 instead of 3. 

Is there is a way to remove the error without using ChangeDetector?

**Comment by lexasq** [comment]
Hi @rchowdev I wasn't able to receive the same error from your code. As for the page reset - it's expected behavior to keep the user on the same page, or if current page exceeds the total number of pages it is set to the last page. This can become a suggestion for new function, but as of now your solution is totally valid for the situation. Just please note that you don't need to set "this.limit = limit" if you are using 2way binding already.
